### ISSUE TITLE
Tabbed browsing

### ISSUE THREAD

**Issue by mindofmatthew** [mindofmatthew/text.management#22]
**Roadmap**
- [X] Basic tab display and multi-file support
- [X] Correct Save/Save As menu behavior
- [x] Implement close behavior (checking for unsaved files etc...)
- [x] Implement correct tab names (with appropriate updates)
- [x] Hide tab bar when no tabs are open
- [x] Re-implement code evaluation/console logging, both of which broke
- [x] Implement menu option/keyboard shortcut for closing current tab (Mod-W)

**Comment by mindofmatthew** [comment]
I'm calling this good enough for now and will file separate issues as they arise.
